Fix build with GCC 4.6 -Werror=unused-but-set-variable
This patch fixes the following build failures:

src/drivers/glamo-mmc.c: In function ‘mmc_write’:
src/drivers/glamo-mmc.c:492:6: error: variable ‘resp’ set but not used [-Werror=unused-but-set-variable]

src/cpu/s3c2442/s3c24xx-mci.c: In function ‘mmc_block_read’:
src/cpu/s3c2442/s3c24xx-mci.c:143:7: error: variable ‘resp’ set but not used [-Werror=unused-but-set-variable]

Signed-off-by: Timo Juhani Lindfors <timo.lindfors@iki.fi>